### ISSUE TITLE
Clarification re terms of use for the segmentations produced by the MRISegmentator model

### ISSUE THREAD

**Issue by fedorov** [rsummers11/MRISegmentator#1]
I understand the license under which the source code in this repository is distributed permits research use only.

Can you please clarify what terms apply to the segmentations produced by this code? Are there any restrictions on the use of these resulting segmentations?

**Comment by YanZhuangNanjing** [comment]
Thank you for your question. The model, code, and its output (e.g., segmentations) are limited to research use only.

**Comment by fedorov** [comment]
Thank you for the clarification.
