### ISSUE TITLE
Missing segmentations

### ISSUE THREAD

**Issue by Leong1230** [rsummers11/MRISegmentator#2]
Hi, thank you for sharing the code! Good job! The segmentation results of my data are amazing.

But I do realize there are some parts that the model ignores (e.g. class 19-26) or fail to segment (10 in my case). The segmentation of vessels inside the liver is important to my project. Do you know why these parts are missing and could you please help in this problem？

![image](https://github.com/user-attachments/assets/a0f31c4c-cdd2-41b2-8213-17978e5bf247)

**Comment by YanZhuangNanjing** [comment]
Hi Leong1230, thank you for your questions. The class 19-26 are the structures in the transitional zones between the abdomen and pelvis. Some abdominal MRIs don’t contain these structures (thus they will not be segmented). Our tool only segments the main portal vein branch (not including the right and left branches). We will add the hepatic vessel segmentation in the future version. If you plan to segment the vessels yourself, I suggest following the pipeline in Fig. 2 in our [manuscript](https://arxiv.org/abs/2405.05944). Namely, (1) training a CT hepatic vessel segmentator using CT hepatic vessel dataset such as the Medical Decathlon, Hepatic Vessel Segmentation dataset;  (2) translating MR images to synthetic CT images; (3) using the CT hepatic vessel segmentator to segment the synthetic CTs and get the pseudo-labels; (4) manually refine these pseudo labels. You can find more details in Fig. 2 (‘For G1&G2 part’) in the manuscript.
